version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-test-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2q8gv1hb920w"
s3_prefix = "sam-test-2"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
